### ISSUE TITLE
Feedback and heartfelt thanks.

### ISSUE THREAD

**Issue by NyamiDev** [teambtcmap/btcmap-general#9]
I love this project! 

I got about ten minutes into your podcast with Sephan and went to the website, dowloaded from F-Droid and started browsing the map. Started telling my family where you can finally buy a coffee locally! This enables me to show, and hopefully demo, use cases in real life for BTC. Finally. Yes.

It is the software I have been searching for and also wanted to make.

You guys are legends for getting it done. Well done. Gonna buy you drinks when hopefully we meet sometime. 

I did some dev work back in the early days of the Apple store as a sideline and rank amateur making some iPhone apps. They located and helped people find locations for the sports I loved. So collating and mapping useful things is very much somethign i find interesting and useful. I wanted to do it avoiding big tech too, but was on Apple, so what to do? It was so much fun though, apart from memory management!  So I have an interest in coding and I love mapping in general and have used OSM originally through MapsWithMe and now OSMand (used via F-Droid). 

I would like to get involved.

However, one initial bit of feedback. There is no 'contact me' area, which is probably intentional as you have kept your website super clean, simple and dam good. I know you don't want spam too. What I really wish from you, and almost all other entities I want to send feedback to is a secure means of communication.

Can I suggest Session at getsession.org? They dont require a phone number like Signal and have a desktop app. I know you might get spammed, not sure how to solve that. Failing Session, maybe use Signal or even PGP or use a Proton.me email, or Tutanota etc. You could use Briar which is proper hardcore but a limited when using at scale perhaps?

I am into mesh networks too and would like to combine your mapping idea with places you can access the internet KYC free and/or with your own node/radio/gateway/goTenna device etc.  These could be combined on the map. Locha.io is also involved in this. 

Now back to the podcast!

**Comment by bubelov** [comment]
@NyamiDev we're all on Discord, currently https://discord.gg/wPqva83uzq

**Comment by secondl1ght** [comment]
@NyamiDev hey I just saw this message now, thanks for the support and I am glad you are finding the apps and project useful! Yes we are currently on Discord but I agree it would be good to use a more private platform in the future, potentially Matrix would be a good option.

I'll close this issue because I am doing a bit of repo cleanup right now but we can continue the discussion here or on our Discord if you joined.
